services:
  - type: web
    name: sentinelmesh-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: REACT_APP_CILIUM_URL
        value: http://localhost:9090
    healthCheckPath: /

  - type: web
    name: sentinelmesh-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile.render
    dockerContext: ./frontend
    plan: free
