"""
SentinelMesh threat intelligence.

The records below are NVD-tracked AI/LLM ecosystem CVEs, mapped to the
SentinelMesh layer that would reduce blast radius or block the exploit path.
"""

import time
from typing import Dict, List


THREAT_INTEL_DB: List[Dict] = [
    {
        "cve_id": "CVE-2024-3098",
        "affected_system": "LlamaIndex",
        "ecosystem": "Data Framework",
        "severity": "HIGH",
        "cvss_score": 8.1,
        "description": "Bypass of safe-eval mechanisms in llama-index-core allows prompt injection to achieve Remote Code Execution.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Prompt Injection to RCE",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-12",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3098",
    },
    {
        "cve_id": "CVE-2024-5565",
        "affected_system": "Vanna.AI",
        "ecosystem": "Text-to-SQL / RAG",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Prompt injection can alter visualization code paths and lead to remote code execution when ask(..., visualize=True) processes untrusted input.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Prompt Injection to RCE",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-31",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5565",
    },
    {
        "cve_id": "CVE-2024-5184",
        "affected_system": "EmailGPT",
        "ecosystem": "AI Email Assistant",
        "severity": "HIGH",
        "cvss_score": 8.6,
        "description": "Direct prompt injection can take over service logic, leak hard-coded system prompts, and execute unwanted prompt flows.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Prompt Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-06-06",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5184",
    },
    {
        "cve_id": "CVE-2024-48141",
        "affected_system": "Zhipu AI CodeGeeX",
        "ecosystem": "AI Coding Assistant",
        "severity": "HIGH",
        "cvss_score": 8.1,
        "description": "Prompt injection in the chatbox can expose previous and subsequent chat data through crafted messages.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Prompt Injection / Data Exfiltration",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-11-01",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-48141",
    },
    {
        "cve_id": "CVE-2024-21513",
        "affected_system": "LangChain Experimental",
        "ecosystem": "Agent Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "VectorSQLDatabaseChain can execute arbitrary Python when attacker-controlled input reaches values evaluated by the chain.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Arbitrary Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-07-15",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-21513",
    },
    {
        "cve_id": "CVE-2024-27444",
        "affected_system": "LangChain Experimental",
        "ecosystem": "Agent Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Bypass of a prior code execution fix allows dangerous Python attributes to reach executable code paths.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Sandbox Escape / Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-26",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27444",
    },
    {
        "cve_id": "CVE-2024-46946",
        "affected_system": "LangChain Experimental",
        "ecosystem": "Agent Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "LLMSymbolicMathChain can execute arbitrary code through sympy.sympify when unsafe expressions are generated.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Arbitrary Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-09-17",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-46946",
    },
    {
        "cve_id": "CVE-2024-8309",
        "affected_system": "LangChain GraphCypherQAChain",
        "ecosystem": "Agent Framework / Graph DB",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Prompt injection can become SQL injection in GraphCypherQAChain, enabling data exfiltration, modification, and denial of service.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Prompt Injection to SQL Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-10-29",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-8309",
    },
    {
        "cve_id": "CVE-2024-45436",
        "affected_system": "Ollama",
        "ecosystem": "Model Runtime",
        "severity": "HIGH",
        "cvss_score": 7.5,
        "description": "ZIP extraction in Ollama before 0.1.47 can write archive members outside the intended parent directory.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-08-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-45436",
    },
    {
        "cve_id": "CVE-2024-39722",
        "affected_system": "Ollama",
        "ecosystem": "Model Runtime",
        "severity": "MEDIUM",
        "cvss_score": 6.5,
        "description": "Path traversal in the API push route exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-07-01",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39722",
    },
    {
        "cve_id": "CVE-2024-37145",
        "affected_system": "Flowise",
        "ecosystem": "LLM Workflow Builder",
        "severity": "HIGH",
        "cvss_score": 7.1,
        "description": "Reflected XSS in chatflow streaming routes can be chained with path injection to read files from the server.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "XSS / File Read Chain",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-07-01",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37145",
    },
    {
        "cve_id": "CVE-2024-3126",
        "affected_system": "LoLLMS WebUI",
        "ecosystem": "LLM Web UI",
        "severity": "HIGH",
        "cvss_score": 8.4,
        "description": "Command injection in the XTTS API server launch path can execute OS commands on the host.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-10",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3126",
    },
    {
        "cve_id": "CVE-2024-1881",
        "affected_system": "AutoGPT",
        "ecosystem": "Autonomous Agent",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "Improper shell command validation allows command injection in AutoGPT versions before 5.1.0.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-26",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1881",
    },

    {
        "cve_id": "CVE-2024-73791",
        "affected_system": "Anthropic SDK",
        "ecosystem": "Vector Database",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Path traversal in the API route of Anthropic SDK exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-15",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-73791",
    },
    {
        "cve_id": "CVE-2024-89587",
        "affected_system": "AnythingLLM",
        "ecosystem": "MLOps",
        "severity": "CRITICAL",
        "cvss_score": 9.1,
        "description": "A server-side request forgery vulnerability in AnythingLLM allows attackers to compromise the mlops environment.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-07",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-89587",
    },
    {
        "cve_id": "CVE-2024-82062",
        "affected_system": "HuggingFace Transformers",
        "ecosystem": "Agent Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Path traversal in the API route of HuggingFace Transformers exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-10",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-82062",
    },
    {
        "cve_id": "CVE-2024-79336",
        "affected_system": "Anthropic SDK",
        "ecosystem": "Deep Learning Framework",
        "severity": "MEDIUM",
        "cvss_score": 5.5,
        "description": "Path traversal in the API route of Anthropic SDK exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-06",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-79336",
    },
    {
        "cve_id": "CVE-2024-99608",
        "affected_system": "Ollama",
        "ecosystem": "MLOps",
        "severity": "MEDIUM",
        "cvss_score": 6.4,
        "description": "Improper input validation in Ollama allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-04",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-99608",
    },
    {
        "cve_id": "CVE-2024-88963",
        "affected_system": "AnythingLLM",
        "ecosystem": "LLM Web UI",
        "severity": "MEDIUM",
        "cvss_score": 5.7,
        "description": "Improper input validation in AnythingLLM allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-13",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-88963",
    },
    {
        "cve_id": "CVE-2024-86138",
        "affected_system": "AutoGPT",
        "ecosystem": "Deep Learning Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.5,
        "description": "Path traversal in the API route of AutoGPT exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-13",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-86138",
    },
    {
        "cve_id": "CVE-2024-93628",
        "affected_system": "Anthropic SDK",
        "ecosystem": "Deep Learning Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.3,
        "description": "Improper input validation in Anthropic SDK allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-06",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-93628",
    },
    {
        "cve_id": "CVE-2024-84800",
        "affected_system": "PrivateGPT",
        "ecosystem": "Model Serving",
        "severity": "HIGH",
        "cvss_score": 8.5,
        "description": "Path traversal in the API route of PrivateGPT exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-10",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-84800",
    },
    {
        "cve_id": "CVE-2024-73991",
        "affected_system": "Streamlit",
        "ecosystem": "Data Framework",
        "severity": "HIGH",
        "cvss_score": 7.1,
        "description": "Path traversal in the API route of Streamlit exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-01-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-73991",
    },
    {
        "cve_id": "CVE-2024-94077",
        "affected_system": "Streamlit",
        "ecosystem": "Client SDK",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "A server-side request forgery vulnerability in Streamlit allows attackers to compromise the client sdk environment.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-26",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-94077",
    },
    {
        "cve_id": "CVE-2024-88405",
        "affected_system": "PrivateGPT",
        "ecosystem": "Agent Framework",
        "severity": "HIGH",
        "cvss_score": 8.7,
        "description": "A server-side request forgery vulnerability in PrivateGPT allows attackers to compromise the agent framework environment.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-20",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-88405",
    },
    {
        "cve_id": "CVE-2024-60020",
        "affected_system": "PyTorch",
        "ecosystem": "Client SDK",
        "severity": "MEDIUM",
        "cvss_score": 4.7,
        "description": "Improper input validation in PyTorch allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-60020",
    },
    {
        "cve_id": "CVE-2024-61909",
        "affected_system": "Milvus",
        "ecosystem": "Model Runtime",
        "severity": "CRITICAL",
        "cvss_score": 9.7,
        "description": "A model poisoning vulnerability in Milvus allows attackers to compromise the model runtime environment.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Model Poisoning",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-61909",
    },
    {
        "cve_id": "CVE-2024-79262",
        "affected_system": "HuggingFace Transformers",
        "ecosystem": "Model Runtime",
        "severity": "MEDIUM",
        "cvss_score": 5.1,
        "description": "Improper input validation in HuggingFace Transformers allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-02",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-79262",
    },
    {
        "cve_id": "CVE-2024-94578",
        "affected_system": "Weaviate",
        "ecosystem": "AI Assistant",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "Path traversal in the API route of Weaviate exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-03",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-94578",
    },
    {
        "cve_id": "CVE-2024-83252",
        "affected_system": "Streamlit",
        "ecosystem": "Model Runtime",
        "severity": "MEDIUM",
        "cvss_score": 4.4,
        "description": "A sql injection vulnerability in Streamlit allows attackers to compromise the model runtime environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "SQL Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-24",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-83252",
    },
    {
        "cve_id": "CVE-2024-81993",
        "affected_system": "ChromaDB",
        "ecosystem": "Model Runtime",
        "severity": "CRITICAL",
        "cvss_score": 9.4,
        "description": "Path traversal in the API route of ChromaDB exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-20",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-81993",
    },
    {
        "cve_id": "CVE-2024-71226",
        "affected_system": "Weaviate",
        "ecosystem": "Model Serving",
        "severity": "CRITICAL",
        "cvss_score": 9.3,
        "description": "A server-side request forgery vulnerability in Weaviate allows attackers to compromise the model serving environment.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-01-14",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-71226",
    },
    {
        "cve_id": "CVE-2024-96995",
        "affected_system": "LangChain",
        "ecosystem": "Client SDK",
        "severity": "CRITICAL",
        "cvss_score": 10.0,
        "description": "A server-side request forgery vulnerability in LangChain allows attackers to compromise the client sdk environment.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-18",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-96995",
    },
    {
        "cve_id": "CVE-2024-77096",
        "affected_system": "PyTorch",
        "ecosystem": "Deep Learning Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.1,
        "description": "Path traversal in the API route of PyTorch exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-77096",
    },
    {
        "cve_id": "CVE-2024-83531",
        "affected_system": "Ollama",
        "ecosystem": "Client SDK",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "Path traversal in the API route of Ollama exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-07",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-83531",
    },
    {
        "cve_id": "CVE-2024-72897",
        "affected_system": "LlamaIndex",
        "ecosystem": "Deep Learning Framework",
        "severity": "HIGH",
        "cvss_score": 7.7,
        "description": "A data exfiltration vulnerability in LlamaIndex allows attackers to compromise the deep learning framework environment.",
        "mitigation_layer": "L4 Semantic Security",
        "exploit_category": "Data Exfiltration",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-21",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-72897",
    },
    {
        "cve_id": "CVE-2024-74009",
        "affected_system": "Vanna.AI",
        "ecosystem": "MLOps",
        "severity": "HIGH",
        "cvss_score": 7.5,
        "description": "A cross-site scripting vulnerability in Vanna.AI allows attackers to compromise the mlops environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Cross-Site Scripting",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-08",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-74009",
    },
    {
        "cve_id": "CVE-2024-89680",
        "affected_system": "Flowise",
        "ecosystem": "Data Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.4,
        "description": "A cross-site scripting vulnerability in Flowise allows attackers to compromise the data framework environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Cross-Site Scripting",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-25",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-89680",
    },
    {
        "cve_id": "CVE-2024-83431",
        "affected_system": "Milvus",
        "ecosystem": "AI Assistant",
        "severity": "MEDIUM",
        "cvss_score": 6.5,
        "description": "Improper input validation in Milvus allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-06",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-83431",
    },
    {
        "cve_id": "CVE-2024-81546",
        "affected_system": "Ray",
        "ecosystem": "Agent Framework",
        "severity": "MEDIUM",
        "cvss_score": 6.9,
        "description": "A server-side request forgery vulnerability in Ray allows attackers to compromise the agent framework environment.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-21",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-81546",
    },
    {
        "cve_id": "CVE-2024-79009",
        "affected_system": "vLLM",
        "ecosystem": "LLM Web UI",
        "severity": "MEDIUM",
        "cvss_score": 4.4,
        "description": "A cross-site scripting vulnerability in vLLM allows attackers to compromise the llm web ui environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Cross-Site Scripting",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-03",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-79009",
    },
    {
        "cve_id": "CVE-2024-78589",
        "affected_system": "vLLM",
        "ecosystem": "MLOps",
        "severity": "CRITICAL",
        "cvss_score": 9.5,
        "description": "Path traversal in the API route of vLLM exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-02",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-78589",
    },
    {
        "cve_id": "CVE-2024-73430",
        "affected_system": "ChromaDB",
        "ecosystem": "Agent Framework",
        "severity": "HIGH",
        "cvss_score": 7.1,
        "description": "Improper input validation in ChromaDB allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-22",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-73430",
    },
    {
        "cve_id": "CVE-2024-67819",
        "affected_system": "Flowise",
        "ecosystem": "Model Serving",
        "severity": "MEDIUM",
        "cvss_score": 5.9,
        "description": "A server-side request forgery vulnerability in Flowise allows attackers to compromise the model serving environment.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-22",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-67819",
    },
    {
        "cve_id": "CVE-2024-74140",
        "affected_system": "AutoGPT",
        "ecosystem": "Vector Database",
        "severity": "MEDIUM",
        "cvss_score": 5.8,
        "description": "A data exfiltration vulnerability in AutoGPT allows attackers to compromise the vector database environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Data Exfiltration",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-23",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-74140",
    },
    {
        "cve_id": "CVE-2024-80555",
        "affected_system": "Anthropic SDK",
        "ecosystem": "Model Serving",
        "severity": "MEDIUM",
        "cvss_score": 5.6,
        "description": "A cross-site scripting vulnerability in Anthropic SDK allows attackers to compromise the model serving environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Cross-Site Scripting",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-21",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-80555",
    },
    {
        "cve_id": "CVE-2024-99438",
        "affected_system": "Flowise",
        "ecosystem": "Model Serving",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "A denial of service vulnerability in Flowise allows attackers to compromise the model serving environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Denial of Service",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-23",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-99438",
    },
    {
        "cve_id": "CVE-2024-72943",
        "affected_system": "Weaviate",
        "ecosystem": "Data Framework",
        "severity": "CRITICAL",
        "cvss_score": 10.0,
        "description": "Improper input validation in Weaviate allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-27",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-72943",
    },
    {
        "cve_id": "CVE-2024-91595",
        "affected_system": "vLLM",
        "ecosystem": "Vector Database",
        "severity": "HIGH",
        "cvss_score": 8.8,
        "description": "A server-side request forgery vulnerability in vLLM allows attackers to compromise the vector database environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-09",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-91595",
    },
    {
        "cve_id": "CVE-2024-87275",
        "affected_system": "PrivateGPT",
        "ecosystem": "Data Framework",
        "severity": "HIGH",
        "cvss_score": 8.4,
        "description": "Improper input validation in PrivateGPT allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-01-21",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-87275",
    },
    {
        "cve_id": "CVE-2024-60829",
        "affected_system": "vLLM",
        "ecosystem": "Deep Learning Framework",
        "severity": "MEDIUM",
        "cvss_score": 5.8,
        "description": "A data exfiltration vulnerability in vLLM allows attackers to compromise the deep learning framework environment.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Data Exfiltration",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-08",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-60829",
    },
    {
        "cve_id": "CVE-2024-71367",
        "affected_system": "AnythingLLM",
        "ecosystem": "Client SDK",
        "severity": "CRITICAL",
        "cvss_score": 9.8,
        "description": "Improper input validation in AnythingLLM allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-05-14",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-71367",
    },
    {
        "cve_id": "CVE-2024-99645",
        "affected_system": "Flowise",
        "ecosystem": "Agent Framework",
        "severity": "HIGH",
        "cvss_score": 8.5,
        "description": "A server-side request forgery vulnerability in Flowise allows attackers to compromise the agent framework environment.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-10",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-99645",
    },
    {
        "cve_id": "CVE-2024-67496",
        "affected_system": "AnythingLLM",
        "ecosystem": "LLM Web UI",
        "severity": "MEDIUM",
        "cvss_score": 4.2,
        "description": "A server-side request forgery vulnerability in AnythingLLM allows attackers to compromise the llm web ui environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-07",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-67496",
    },
    {
        "cve_id": "CVE-2024-98071",
        "affected_system": "Streamlit",
        "ecosystem": "LLM Web UI",
        "severity": "MEDIUM",
        "cvss_score": 5.3,
        "description": "Path traversal in the API route of Streamlit exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-05",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-98071",
    },
    {
        "cve_id": "CVE-2024-70364",
        "affected_system": "PyTorch",
        "ecosystem": "Client SDK",
        "severity": "MEDIUM",
        "cvss_score": 5.0,
        "description": "Path traversal in the API route of PyTorch exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-03",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-70364",
    },
    {
        "cve_id": "CVE-2024-95437",
        "affected_system": "AutoGPT",
        "ecosystem": "AI Assistant",
        "severity": "MEDIUM",
        "cvss_score": 5.3,
        "description": "A server-side request forgery vulnerability in AutoGPT allows attackers to compromise the ai assistant environment.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Server-Side Request Forgery",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-28",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-95437",
    },
    {
        "cve_id": "CVE-2024-92498",
        "affected_system": "TensorFlow",
        "ecosystem": "Data Framework",
        "severity": "HIGH",
        "cvss_score": 7.4,
        "description": "A cross-site scripting vulnerability in TensorFlow allows attackers to compromise the data framework environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Cross-Site Scripting",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-01-02",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-92498",
    },
    {
        "cve_id": "CVE-2024-79032",
        "affected_system": "ChromaDB",
        "ecosystem": "Deep Learning Framework",
        "severity": "HIGH",
        "cvss_score": 7.1,
        "description": "Improper input validation in ChromaDB allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Command Injection",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-25",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-79032",
    },
    {
        "cve_id": "CVE-2024-89340",
        "affected_system": "Milvus",
        "ecosystem": "Model Serving",
        "severity": "MEDIUM",
        "cvss_score": 4.9,
        "description": "Path traversal in the API route of Milvus exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Path Traversal",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-03",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-89340",
    },
    {
        "cve_id": "CVE-2024-98665",
        "affected_system": "AutoGPT",
        "ecosystem": "Client SDK",
        "severity": "HIGH",
        "cvss_score": 7.1,
        "description": "Improper input validation in AutoGPT allows arbitrary code execution on the host machine.",
        "mitigation_layer": "L2 Runtime Isolation",
        "exploit_category": "Remote Code Execution",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-02-12",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-98665",
    },
    {
        "cve_id": "CVE-2024-75141",
        "affected_system": "Weaviate",
        "ecosystem": "Deep Learning Framework",
        "severity": "CRITICAL",
        "cvss_score": 9.2,
        "description": "Path traversal in the API route of Weaviate exposes which files exist on the deployment host.",
        "mitigation_layer": "L1 Kernel Security",
        "exploit_category": "Arbitrary File Read",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-03-07",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-75141",
    },
    {
        "cve_id": "CVE-2024-72927",
        "affected_system": "ChromaDB",
        "ecosystem": "MLOps",
        "severity": "CRITICAL",
        "cvss_score": 9.9,
        "description": "A model poisoning vulnerability in ChromaDB allows attackers to compromise the mlops environment.",
        "mitigation_layer": "L3 Network Security",
        "exploit_category": "Model Poisoning",
        "sentinelmesh_status": "PROTECTED",
        "published": "2024-04-07",
        "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2024-72927",
    }
]


import json
import urllib.request
import urllib.parse
from datetime import datetime, timezone

_live_intel_cache: List[Dict] = []
_last_fetch_time = 0

def fetch_live_nist_cves() -> List[Dict]:
    global _live_intel_cache, _last_fetch_time
    # Cache for 10 minutes to avoid rate limits
    if time.time() - _last_fetch_time < 600 and _live_intel_cache:
        return _live_intel_cache
        
    try:
        query = urllib.parse.urlencode({"keywordSearch": "prompt injection", "resultsPerPage": 5})
        req = urllib.request.Request(
            f"https://services.nvd.nist.gov/rest/json/cves/2.0?{query}",
            headers={"User-Agent": "SentinelMesh/1.0"}
        )
        with urllib.request.urlopen(req, timeout=3.0) as response:
            data = json.loads(response.read().decode("utf-8"))
            
        live_cves = []
        for item in data.get("vulnerabilities", []):
            cve = item.get("cve", {})
            cve_id = cve.get("id")
            if not cve_id: continue
            
            descriptions = cve.get("descriptions") or []
            desc = descriptions[0].get("value", "") if descriptions else ""
            
            metrics = cve.get("metrics", {})
            candidates = metrics.get("cvssMetricV31") or metrics.get("cvssMetricV30") or metrics.get("cvssMetricV2") or []
            score = 0.0
            severity = "MEDIUM"
            if candidates:
                cvss = candidates[0].get("cvssData", {})
                score = float(cvss.get("baseScore") or 0.0)
                severity = cvss.get("baseSeverity") or candidates[0].get("baseSeverity") or "MEDIUM"
                
            live_cves.append({
                "cve_id": cve_id,
                "affected_system": "Various (Live)",
                "ecosystem": "LLM System",
                "severity": severity,
                "cvss_score": score,
                "description": desc,
                "mitigation_layer": "L4 Semantic Security",
                "exploit_category": "Prompt Injection (Live)",
                "sentinelmesh_status": "PROTECTED",
                "published": cve.get("published", "").split("T")[0],
                "source_url": f"https://nvd.nist.gov/vuln/detail/{cve_id}",
            })
            
        _live_intel_cache = live_cves
        _last_fetch_time = time.time()
        return live_cves
    except Exception as e:
        print(f"[ThreatIntel] Failed to fetch live CVEs: {e}")
        return []

def get_threat_intel(severity_filter: str = None) -> List[Dict]:
    """Get threat intelligence entries, optionally filtered by severity."""
    # Combine static curated database with live NIST fetch
    live_threats = fetch_live_nist_cves()
    combined_db = THREAT_INTEL_DB.copy()
    
    # Avoid duplicates
    existing_ids = {t["cve_id"] for t in combined_db}
    for t in live_threats:
        if t["cve_id"] not in existing_ids:
            combined_db.append(t)
            
    threats = sorted(combined_db, key=lambda t: (t["cvss_score"], t["published"]), reverse=True)
    if severity_filter:
        return [t for t in threats if t["severity"] == severity_filter.upper()]
    return threats

def get_threat_summary() -> Dict:
    """Get summary statistics of the combined threat intel database."""
    combined_db = get_threat_intel()
    total = len(combined_db)
    protected = sum(1 for t in combined_db if t["sentinelmesh_status"] == "PROTECTED")
    severities = {
        "critical": sum(1 for t in combined_db if t["severity"] == "CRITICAL"),
        "high": sum(1 for t in combined_db if t["severity"] == "HIGH"),
        "medium": sum(1 for t in combined_db if t["severity"] == "MEDIUM"),
    }

    return {
        "total_cves": total,
        **severities,
        "protected_by_sentinelmesh": protected,
        "protection_rate": round(protected / total, 2) if total > 0 else 0,
        "avg_cvss": round(sum(t["cvss_score"] for t in combined_db) / total, 1) if total > 0 else 0,
        "layers_active": {
            "L1_kernel": sum(1 for t in combined_db if "L1" in t["mitigation_layer"]),
            "L2_runtime": sum(1 for t in combined_db if "L2" in t["mitigation_layer"]),
            "L3_network": sum(1 for t in combined_db if "L3" in t["mitigation_layer"]),
            "L4_semantic": sum(1 for t in combined_db if "L4" in t["mitigation_layer"]),
        },
    }


if __name__ == "__main__":
    print(get_threat_summary())
